export type Product = {
  id: number
  name: string
  type: 'book' | 'toy'
  category: string
  author?: string
  ageRange: string
  price: number
  rating: number
  reviews: number
  image: string
  badge?: string
  description: string
}

export const heroSlides = [
  {
    id: 1,
    title: 'Welcome to Appu World!',
    subtitle: "Books & Toys for Every Age, Every Story",
    description: 'Explore our curated collection of 8,000+ books for all ages — from picture books for toddlers to bestselling novels for adults — plus 1,000+ educational toys.',
    cta: 'Explore Now',
    ctaHref: '/products',
    secondaryCta: 'Join Membership',
    secondaryCtaHref: '/membership',
    image: 'https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=1400&q=80',
    gradient: 'from-emerald-900/70 via-emerald-700/50 to-transparent',
  },
  {
    id: 2,
    title: 'A Book for Every Reader',
    subtitle: 'Over 8,000 Titles — Kids to Adults',
    description: 'From picture books and young adult fiction to self-help, biographies, thrillers, and classics — hand-curated stories that inspire every reader at every stage of life.',
    cta: 'Browse Books',
    ctaHref: '/products?category=books',
    secondaryCta: 'View Plans',
    secondaryCtaHref: '/membership',
    image: 'https://images.unsplash.com/photo-1524578271613-d550eacf6090?w=1400&q=80',
    gradient: 'from-emerald-900/70 via-emerald-700/50 to-transparent',
  },
  {
    id: 3,
    title: 'Fun & Educational Toys',
    subtitle: 'Learning Through Play, Every Single Day',
    description: 'Handpicked toys that make learning an adventure. Safe, engaging, and perfect for every age group from 0 to 14 years.',
    cta: 'Borrow Toys',
    ctaHref: '/products?category=toys',
    secondaryCta: 'Learn More',
    secondaryCtaHref: '/membership',
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=1400&q=80',
    gradient: 'from-emerald-900/70 via-emerald-700/50 to-transparent',
  },
]

export const books: Product[] = [
  // Children's books
  {
    id: 1,
    name: 'The Very Hungry Caterpillar',
    type: 'book',
    category: 'Picture Books',
    author: 'Eric Carle',
    ageRange: '2–5 years',
    price: 299,
    rating: 5,
    reviews: 2840,
    image: 'https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=400&q=80',
    badge: 'Bestseller',
    description: "A timeless classic about a caterpillar's colorful journey through food.",
  },
  {
    id: 2,
    name: 'Goodnight Moon',
    type: 'book',
    category: 'Picture Books',
    author: 'Margaret Wise Brown',
    ageRange: '0–3 years',
    price: 249,
    rating: 5,
    reviews: 1920,
    image: 'https://images.unsplash.com/photo-1543002588-bfa74002ed7e?w=400&q=80',
    badge: 'Classic',
    description: 'A soothing bedtime story loved by generations of children.',
  },
  {
    id: 3,
    name: 'Where the Wild Things Are',
    type: 'book',
    category: 'Picture Books',
    author: 'Maurice Sendak',
    ageRange: '3–7 years',
    price: 349,
    rating: 5,
    reviews: 3210,
    image: 'https://images.unsplash.com/photo-1512820790803-83ca734da794?w=400&q=80',
    badge: 'Award Winner',
    description: 'A wild adventure of imagination and the comfort of home.',
  },
  {
    id: 4,
    name: 'My First ABC Book',
    type: 'book',
    category: 'Learning',
    author: 'Various',
    ageRange: '2–4 years',
    price: 199,
    rating: 4,
    reviews: 1540,
    image: 'https://images.unsplash.com/photo-1456513080510-7bf3a84b82f8?w=400&q=80',
    description: 'Fun and colorful introduction to the alphabet for toddlers.',
  },
  {
    id: 5,
    name: 'Charlie and the Chocolate Factory',
    type: 'book',
    category: 'Adventure',
    author: 'Roald Dahl',
    ageRange: '8–12 years',
    price: 399,
    rating: 5,
    reviews: 4590,
    image: 'https://images.unsplash.com/photo-1495640388908-05fa85288e61?w=400&q=80',
    badge: 'Must Read',
    description: 'An unforgettable journey into the world of Willy Wonka.',
  },
  {
    id: 6,
    name: 'Panchatantra Tales',
    type: 'book',
    category: 'Stories',
    author: 'Traditional',
    ageRange: '5–10 years',
    price: 299,
    rating: 5,
    reviews: 2100,
    image: 'https://images.unsplash.com/photo-1529158062015-cad636e205a0?w=400&q=80',
    badge: 'Heritage',
    description: 'Ancient wisdom through delightful animal fables.',
  },
  {
    id: 7,
    name: 'The Magic Tree House',
    type: 'book',
    category: 'Adventure',
    author: 'Mary Pope Osborne',
    ageRange: '6–10 years',
    price: 349,
    rating: 4,
    reviews: 2780,
    image: 'https://images.unsplash.com/photo-1533669955142-6a73332af4db?w=400&q=80',
    description: 'Time-travel adventures that make history exciting for kids.',
  },
  {
    id: 8,
    name: 'My First Science Encyclopedia',
    type: 'book',
    category: 'Learning',
    author: 'DK Publishing',
    ageRange: '6–10 years',
    price: 449,
    rating: 5,
    reviews: 1890,
    image: 'https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=400&q=80',
    badge: 'Educational',
    description: 'Visual encyclopedia introducing young minds to the world of science.',
  },
  // Young Adult
  {
    id: 17,
    name: "Harry Potter & the Philosopher's Stone",
    type: 'book',
    category: 'Young Adult',
    author: 'J.K. Rowling',
    ageRange: '10+ years',
    price: 399,
    rating: 5,
    reviews: 24500,
    image: 'https://images.unsplash.com/photo-1512820790803-83ca734da794?w=400&q=80',
    badge: 'All-Time Favourite',
    description: 'The story that made a generation fall in love with reading.',
  },
  {
    id: 18,
    name: 'The Hunger Games',
    type: 'book',
    category: 'Young Adult',
    author: 'Suzanne Collins',
    ageRange: '13+ years',
    price: 449,
    rating: 5,
    reviews: 18200,
    image: 'https://images.unsplash.com/photo-1495640388908-05fa85288e61?w=400&q=80',
    badge: 'Bestseller',
    description: 'A gripping dystopian adventure about survival, courage, and rebellion.',
  },
  // Fiction (Adult)
  {
    id: 19,
    name: 'The Alchemist',
    type: 'book',
    category: 'Fiction',
    author: 'Paulo Coelho',
    ageRange: '14+ years',
    price: 349,
    rating: 5,
    reviews: 19800,
    image: 'https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=400&q=80',
    badge: 'Classic',
    description: "A fable about following your dreams and listening to your heart.",
  },
  {
    id: 20,
    name: 'The Kite Runner',
    type: 'book',
    category: 'Fiction',
    author: 'Khaled Hosseini',
    ageRange: '16+ years',
    price: 399,
    rating: 5,
    reviews: 11400,
    image: 'https://images.unsplash.com/photo-1543002588-bfa74002ed7e?w=400&q=80',
    badge: 'Award Winner',
    description: 'A powerful story of friendship, betrayal, and redemption set in Afghanistan.',
  },
  {
    id: 21,
    name: 'The Great Gatsby',
    type: 'book',
    category: 'Fiction',
    author: 'F. Scott Fitzgerald',
    ageRange: '16+ years',
    price: 299,
    rating: 4,
    reviews: 6700,
    image: 'https://images.unsplash.com/photo-1533669955142-6a73332af4db?w=400&q=80',
    badge: 'Classic',
    description: 'A portrait of the Jazz Age in all its decadence and excess.',
  },
  // Non Fiction
  {
    id: 22,
    name: 'Sapiens',
    type: 'book',
    category: 'Non Fiction',
    author: 'Yuval Noah Harari',
    ageRange: '16+ years',
    price: 599,
    rating: 5,
    reviews: 9800,
    image: 'https://images.unsplash.com/photo-1456513080510-7bf3a84b82f8?w=400&q=80',
    badge: 'Must Read',
    description: 'A brief history of humankind — from ancient humans to the modern world.',
  },
  {
    id: 23,
    name: 'Thinking, Fast and Slow',
    type: 'book',
    category: 'Non Fiction',
    author: 'Daniel Kahneman',
    ageRange: '18+ years',
    price: 549,
    rating: 5,
    reviews: 7600,
    image: 'https://images.unsplash.com/photo-1529158062015-cad636e205a0?w=400&q=80',
    badge: 'Nobel Laureate',
    description: 'A groundbreaking tour of the mind and an exploration of rational thought.',
  },
  // Self Help
  {
    id: 24,
    name: 'Atomic Habits',
    type: 'book',
    category: 'Self Help',
    author: 'James Clear',
    ageRange: '16+ years',
    price: 499,
    rating: 5,
    reviews: 14200,
    image: 'https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=400&q=80',
    badge: 'Bestseller',
    description: 'Tiny changes, remarkable results. The definitive guide to building good habits.',
  },
  {
    id: 25,
    name: 'Rich Dad Poor Dad',
    type: 'book',
    category: 'Self Help',
    author: 'Robert T. Kiyosaki',
    ageRange: '16+ years',
    price: 399,
    rating: 5,
    reviews: 11200,
    image: 'https://images.unsplash.com/photo-1512820790803-83ca734da794?w=400&q=80',
    badge: 'Finance',
    description: 'What the rich teach their kids about money that the poor and middle class do not.',
  },
  // Biography
  {
    id: 26,
    name: 'Wings of Fire',
    type: 'book',
    category: 'Biography',
    author: 'A.P.J. Abdul Kalam',
    ageRange: '14+ years',
    price: 299,
    rating: 5,
    reviews: 15600,
    image: 'https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?w=400&q=80',
    badge: 'Inspiring',
    description: "The autobiography of India's Missile Man and former President.",
  },
  {
    id: 27,
    name: 'Steve Jobs',
    type: 'book',
    category: 'Biography',
    author: 'Walter Isaacson',
    ageRange: '16+ years',
    price: 649,
    rating: 5,
    reviews: 9100,
    image: 'https://images.unsplash.com/photo-1495640388908-05fa85288e61?w=400&q=80',
    badge: 'Icon',
    description: 'The exclusive biography of Apple co-founder Steve Jobs.',
  },
  // Mystery / Thriller
  {
    id: 28,
    name: 'The Silent Patient',
    type: 'book',
    category: 'Mystery',
    author: 'Alex Michaelides',
    ageRange: '18+ years',
    price: 449,
    rating: 5,
    reviews: 8900,
    image: 'https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=400&q=80',
    badge: 'Thriller',
    description: "A gripping psychological thriller with a twist you'll never see coming.",
  },
  {
    id: 29,
    name: 'Gone Girl',
    type: 'book',
    category: 'Mystery',
    author: 'Gillian Flynn',
    ageRange: '18+ years',
    price: 399,
    rating: 4,
    reviews: 7300,
    image: 'https://images.unsplash.com/photo-1533669955142-6a73332af4db?w=400&q=80',
    badge: 'Gripping',
    description: 'A dark, twisty tale of a marriage gone terribly, frighteningly wrong.',
  },
]

export const toys: Product[] = [
  {
    id: 9,
    name: 'Rainbow Building Blocks Set',
    type: 'toy',
    category: 'Educational',
    ageRange: '2–6 years',
    price: 599,
    rating: 5,
    reviews: 3420,
    image: 'https://images.unsplash.com/photo-1611532736597-de2d4265fba3?w=400&q=80',
    badge: 'Bestseller',
    description: '100-piece colorful wooden blocks for creative building and learning.',
  },
  {
    id: 10,
    name: '100-Piece Puzzle Adventure Set',
    type: 'toy',
    category: 'Educational',
    ageRange: '5–10 years',
    price: 449,
    rating: 5,
    reviews: 2150,
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&q=80',
    badge: 'Brain Booster',
    description: 'Educational puzzles featuring animals, maps, and space themes.',
  },
  {
    id: 11,
    name: 'Complete Art & Craft Kit',
    type: 'toy',
    category: 'Creative',
    ageRange: '4–12 years',
    price: 699,
    rating: 4,
    reviews: 1870,
    image: 'https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?w=400&q=80',
    description: 'All-in-one creative kit with paints, brushes, clay, and more.',
  },
  {
    id: 12,
    name: 'Little Doctor Play Set',
    type: 'toy',
    category: 'Role Play',
    ageRange: '3–8 years',
    price: 549,
    rating: 4,
    reviews: 1320,
    image: 'https://images.unsplash.com/photo-1587654780291-39c9404d746b?w=400&q=80',
    description: 'Complete doctor kit to inspire future healers with safe tools.',
  },
  {
    id: 13,
    name: 'Mini Chef Kitchen Set',
    type: 'toy',
    category: 'Role Play',
    ageRange: '3–8 years',
    price: 799,
    rating: 5,
    reviews: 2340,
    image: 'https://images.unsplash.com/photo-1595159741926-571e24e8c7e0?w=400&q=80',
    badge: 'Popular',
    description: 'Realistic kitchen playset with 35+ accessories for pretend cooking.',
  },
  {
    id: 14,
    name: 'Junior Science Experiment Kit',
    type: 'toy',
    category: 'Educational',
    ageRange: '8–14 years',
    price: 899,
    rating: 5,
    reviews: 1560,
    image: 'https://images.unsplash.com/photo-1615791680466-6fad8dce5f82?w=400&q=80',
    badge: 'STEM',
    description: '20 exciting science experiments to ignite curiosity and learning.',
  },
  {
    id: 15,
    name: 'Musical Instruments Starter Set',
    type: 'toy',
    category: 'Creative',
    ageRange: '2–6 years',
    price: 649,
    rating: 5,
    reviews: 2010,
    image: 'https://images.unsplash.com/photo-1514320291840-2e0a9bf2a9ae?w=400&q=80',
    description: '8-piece musical set including drums, xylophone, and maracas.',
  },
  {
    id: 16,
    name: 'Mega Builder Construction Set',
    type: 'toy',
    category: 'Educational',
    ageRange: '5–14 years',
    price: 1199,
    rating: 5,
    reviews: 4230,
    image: 'https://images.unsplash.com/photo-1587654780291-39c9404d746b?w=400&q=80',
    badge: 'Premium',
    description: '500-piece building block set for endless creative constructions.',
  },
]

export const testimonials = [
  {
    id: 1,
    name: 'Priya Sharma',
    location: 'Bangalore',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&h=100&fit=crop&q=80',
    rating: 5,
    text: "Appu World has transformed my daughter's love for reading! The children's book selection is incredible and the toys are so educational. Best investment for our family!",
    role: 'Parent of a 5-year-old',
  },
  {
    id: 2,
    name: 'Rahul Mehta',
    location: 'Mumbai',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&h=100&fit=crop&q=80',
    rating: 5,
    text: 'I joined for my kids but ended up borrowing novels for myself too! The adult fiction and non-fiction section is just as impressive. Worth every rupee of the membership.',
    role: 'Software Engineer & avid reader',
  },
  {
    id: 3,
    name: 'Anitha Kumar',
    location: 'Chennai',
    avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100&h=100&fit=crop&q=80',
    rating: 5,
    text: "The staff is so helpful and the collection is amazing! My twins love the children's section, and I discovered some brilliant self-help books I wouldn't have found otherwise.",
    role: 'Parent & self-help enthusiast',
  },
  {
    id: 4,
    name: 'Vikram Nair',
    location: 'Hyderabad',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&h=100&fit=crop&q=80',
    rating: 5,
    text: "As someone who reads 2–3 books a month, the membership pays for itself in a week. The biography and thriller collections are excellent. Highly recommend to any book lover.",
    role: 'Business Analyst & book club member',
  },
  {
    id: 5,
    name: 'Meera Reddy',
    location: 'Pune',
    avatar: 'https://images.unsplash.com/photo-1544725176-7c40e5a71c5e?w=100&h=100&fit=crop&q=80',
    rating: 5,
    text: "We've been members for 2 years now. My children explore picture books while I catch up on the latest fiction. New arrivals each month keep all of us excited!",
    role: 'Parent of two (4 & 9 years)',
  },
]

export const membershipPlans = [
  {
    id: 1,
    name: 'Starter',
    price: 499,
    yearlyPrice: 4790,
    tagline: 'Perfect to get started',
    colorFrom: 'from-emerald-400',
    colorTo: 'to-emerald-500',
    textColor: 'text-emerald-500',
    bgLight: 'bg-emerald-50',
    borderColor: 'border-emerald-200',
    features: [
      { text: '5 Books per month (any age/genre)', included: true },
      { text: '1 Toy rental per month', included: true },
      { text: 'Access to Reading Corner', included: true },
      { text: 'Monthly newsletter', included: true },
      { text: 'Basic email support', included: true },
      { text: 'Early access to new arrivals', included: false },
      { text: 'Story time & author events', included: false },
      { text: 'Birthday surprise gift', included: false },
    ],
    popular: false,
    cta: 'Get Started',
  },
  {
    id: 2,
    name: 'Explorer',
    price: 799,
    yearlyPrice: 7670,
    tagline: 'Best for growing readers',
    colorFrom: 'from-emerald-500',
    colorTo: 'to-emerald-600',
    textColor: 'text-emerald-500',
    bgLight: 'bg-emerald-50',
    borderColor: 'border-emerald-300',
    features: [
      { text: '10 Books per month (any age/genre)', included: true },
      { text: '3 Toy rentals per month', included: true },
      { text: 'Access to Reading Corner', included: true },
      { text: 'Weekly newsletter & recommendations', included: true },
      { text: 'Priority email support', included: true },
      { text: 'Early access to new arrivals', included: true },
      { text: 'Monthly story time & events', included: true },
      { text: 'Birthday surprise gift', included: false },
    ],
    popular: true,
    cta: 'Most Popular',
  },
  {
    id: 3,
    name: 'Champion',
    price: 1199,
    yearlyPrice: 11510,
    tagline: 'Ultimate reading experience',
    colorFrom: 'from-emerald-600',
    colorTo: 'to-emerald-700',
    textColor: 'text-emerald-700',
    bgLight: 'bg-emerald-50',
    borderColor: 'border-emerald-300',
    features: [
      { text: 'Unlimited Books (any age/genre)', included: true },
      { text: '5 Toy rentals per month', included: true },
      { text: 'VIP Reading Corner access', included: true },
      { text: 'Daily curated recommendations', included: true },
      { text: '24/7 premium support', included: true },
      { text: 'First access to all new arrivals', included: true },
      { text: 'Weekly events & author sessions', included: true },
      { text: 'Annual birthday surprise gift', included: true },
    ],
    popular: false,
    cta: 'Go Premium',
  },
]
